// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

type Board struct {
	ID    int32
	Name  string
	Owner string
}

type Column struct {
	ID       int32
	Name     string
	BoardID  int32
	Position int32
}

type Task struct {
	ID       int32
	Title    string
	ColumnID int32
	Position int32
}

type TaskDependency struct {
	TaskID      int32
	DependsOnID int32
}

type User struct {
	Username     string
	PasswordHash string
	Admin        bool
}
